apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-admin
  namespace: ecommerce
  labels:
    app: ecommerce-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-admin
  template:
    metadata:
      labels:
        app: ecommerce-admin
    spec:
      containers:
        - name: ecommerce-admin
          image: jhormanmera/ecommerce-admin
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLERK-PUBLISHABLE-KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: CLERK-SECRET-KEY
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLERK-SIGN-IN-URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLERK-AFTER-SIGN-IN-URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: DATABASE-URL
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLOUDINARY-CLOUD-NAME
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLERK-SIGN-UP-URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: NEXT-PUBLIC-CLERK-AFTER-SIGN-UP-URL
            - name: CLOUDINARY_PRESET_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: CLOUDINARY-PRESET-NAME
            - name: FRONTEND_STORE_URL
              value: "http://ecommerce-store:3001"
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: STRIPE-API-KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: STRIPE-WEBHOOK-SECRET
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-admin
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-admin
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-store
  namespace: ecommerce
  labels:
    app: ecommerce-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-store
  template:
    metadata:
      labels:
        app: ecommerce-store
    spec:
      containers:
        - name: ecommerce-store
          image: jhormanmera/ecommerce-store
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://ecommerce-admin:3000/api/cec6cf95-abd3-419e-a223-5c85cbbb0370"
            - name: REACT_EDITOR
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: REACT-EDITOR
            - name: BILLBOARD_ID
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: BILLBOARD-ID
          volumeMounts:
            - name: secrets-store-inline-store
              mountPath: /mnt/secrets-store/store
              readOnly: true
      volumes:
        - name: secrets-store-inline-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-store
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-store
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP